### ISSUE TITLE
Little bug with Progress Export Files

### ISSUE THREAD

**Issue by gbonazzoli** [dbro/csvquote#11] opened 2017-04-24 07:44 UTC
Progress Database default file export format uses a "blank space" as field separator and uses the double quote char as string delimiter. If you use:
 
csvquote -d ' '

you corrupt the file as every space character will be replaced in every row.

So this is the case:

root@srv-zfs:/samba/public/progress/dump# csvquote a.d
"01010001" 01/01/01 ? "SOCIO SERVICOM C/SOTTOSCRIZIONE" "" "" "" "" "" "" "" "" 0 0
"01010002" 01/01/01 ? "SOCIO ELETTRO 2000 C/SOTTOSCRIZIONE" "" "" "" "" "" "" "" "" 0 0

root@srv-zfs:/samba/public/progress/dump# csvquote a.d -d ' '
"01010001" 01/01/01 ? "SOCIOSERVICOMC/SOTTOSCRIZIONE" "" "" "" "" "" "" "" "" 0 0
"01010002" 01/01/01 ? "SOCIOELETTRO2000C/SOTTOSCRIZIONE" "" "" "" "" "" "" "" "" 0 0

**Comment by dbro** [comment] 2017-04-25 19:56
Hello - this is the intended behavior. Using just the one `csvquote` command in a pipeline does not make much sense. It is meant to be paired with a corresponding `csvquote -u` command at the end of the pipeline, which will translate the file back to use the delimiters you want. In the examples you sent, using just the first `csvquote` command will result in the quoted delimiters "disappearing" from the terminal representation of the data, because the terminal does not display non-printing characters. If you display the raw output using a hex representation, then you will see the delimiters inside the quoted fields. Try this:
> csvquote a.d -d ' ' | hexdump

I'll close this now. Feel free to respond with the full pipeline or description of what you are trying to do.

Dan

**Closed by dbro** 2017-04-25 19:56 UTC

**Comment by gbonazzoli** [comment] 2017-04-25 20:18
Thanks,

I can confirm all the things you said.

Now blank spaces are back again!

root@srv-zfs:/samba/public/progress/dump# cat a.d | csvquote -d ' ' |
csvquote -d ' ' -u

"OR" 22645 1 "ACCANTONATI PER CALANDRINI &" "OR" yes 07/03/13 "" "SEDE"

"OR" 22645 2 "ARDINI , OK DI AGOSTINI , IN" "" yes 07/03/13 "" "SEDE"

"OR" 22645 3 "ATTESA DI SBLOCCO" "" yes 07/03/13 "" "SEDE"

"NE" 33621 1 "OTTOBRE 2013" "NE" yes 18/11/13 "" "SEDE"
